# fly.toml app configuration file generated for quiet-cloud-2130 on 2023-07-02T00:20:23+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-cloud-2130"
primary_region = "mad"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
