import Head from "next/head";
import Image from "next/image";
import { Roboto } from "next/font/google";
import styles from "@/styles/Home.module.css";
import GameLayout from "@/layouts/GameLayout";
const roboto = Roboto({ subsets: ["latin"], weight: "400" });
import { data} from '../utils/helper'
import { useLoginContext } from "@/context/LoginContext";

export default function Home() {

  const { handleLogin, handleSubmit, loginData, error } = useLoginContext();
  

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <GameLayout name="Home" />

      <div className={styles.container}>
        <h1>{error}</h1>
        <form onSubmit={handleSubmit} className={styles.form}>
          <Image
            className={styles.logo}
            width={80}
            height={80}
            src={"/images/logo-master.png"}
            alt="logo-master-question"
          />
          <input
            onChange={handleLogin}
            name="email"
            type="text"
            placeholder="Username"
            value={loginData.email}
          />
          <input
            onChange={handleLogin}
            name="password"
            type="password"
            placeholder="Password"
            value={loginData.password}
          />
          <input className={styles.btn} type="submit" value="Login" />
        </form>
      </div>
    </>
  );
}
